version: '3.7'

volumes:
  postgres_data:

services:
    postgres:
      image: postgres:12.0
      environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGPORT=${DB_PORT}
      - POSTGRES_USER=${DB_USER}
      env_file:
      - .env
      volumes:
        - postgres_data:/var/lib/postgresql/data/

    api:
      build:
        context: .
      command: npm run dev
      env_file:
      - .env
      ports:
        - ${APP_PORT}:${APP_PORT}
        - 8181:8181
      volumes:
        - .:/usr/src/app
      depends_on:
        - postgres